# ── ETAPA 1: Compilación ───────────────────────────────────────────────────
FROM eclipse-temurin:25-jdk-alpine AS builder

WORKDIR /workspace

COPY gradlew .
COPY gradle/ gradle/
COPY build.gradle .
COPY settings.gradle .
RUN chmod +x gradlew
RUN ./gradlew dependencies --no-daemon

COPY src/ src/
RUN ./gradlew bootJar --no-daemon -x test

# ── ETAPA 2: Runtime ───────────────────────────────────────────────────────
FROM eclipse-temurin:25-jdk-alpine AS runtime

WORKDIR /app
RUN mkdir -p /app/data

COPY --from=builder /workspace/build/libs/*.jar app.jar

EXPOSE 8080
ENV SERVER_PORT=8080
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Dserver.port=${SERVER_PORT} -jar app.jar"]